# Generated by Django 4.1.4 on 2022-12-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(max_length=80, verbose_name='Môn học'),
        ),
    ]
